# Generated by Django 3.1.5 on 2021-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('service_type', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('s_center_name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '"oil"."chrono_data"',
            },
        ),
        migrations.CreateModel(
            name='ClientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=10)),
                ('club_name', models.CharField(max_length=50)),
                ('car_brand_name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=70)),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '"oil"."clients_data"',
            },
        ),
        migrations.CreateModel(
            name='ClubAdminsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': '"oil"."club_admins"',
            },
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
    ]
